name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          touch test.a
      - name: 2.推送
        uses: JasonEtco/upload-to-release@master
        with:
          args: test.a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
