name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: 1.准备环境
        run: |
          touch test.a
      - name: Upload SGSI to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: test.a
          name: "test"
          tag: "test"
          bodyFile: ""
          token: ${{ secrets.GITHUB_TOKEN }}
